version: '3.4'

##################################################
# """Extension fields"""
# Environment variables are defined inside the `.env` file.
##################################################
x-image:
    &default-image
    image: infnpd/mucoll-ilc-framework:1.0-centos8

x-volumes:
    &default-volumes
    volumes:
        - $PWD/inputs/SoftCheck:$MAINDIR
        - $PWD/files/xml:$MAINDIR/xml

x-environment:
    &default-environment
    environment:
        - DISPLAY=host.docker.internal:0

services:
    interactive:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash
    simulation:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash -c "source $SOURCE_ILC_FILE && cd $MAINDIR && ddsim --steeringFile $SIM_STEERING_FILE > $SIM_OUTPUT"
    reco:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash -c "source $SOURCE_ILC_FILE && cd $MAINDIR && Marlin $RECO_CONFIG_XML > $RECO_OUTPUT"
    root:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        privileged: true
        command: root