version: '3'

services:
    interactive:
        image: infnpd/mucoll-ilc-framework:1.0-centos8
        command: /bin/bash
    simulation:
        image: infnpd/mucoll-ilc-framework:1.0-centos8
        volumes:
            - $PWD/inputs/SoftCheck:/mnt
        command: /bin/bash -c "source /opt/ilcsoft/v02-01-pre/init_ilcsoft.sh && cd /mnt && ddsim --steeringFile clic_steer.py > sim.out"
    reco:
        image: infnpd/mucoll-ilc-framework:1.0-centos8
        volumes:
            - $PWD/inputs/SoftCheck:/mnt
        command: /bin/bash -c "source /opt/ilcsoft/v02-01-pre/init_ilcsoft.sh && cd /mnt && Marlin RecoConf.xml > reco.out"
    root:
        environment:
            - DISPLAY=host.docker.internal:0
        image: infnpd/mucoll-ilc-framework:1.0-centos8
        privileged: true
        volumes:
            - $PWD/inputs/SoftCheck:/mnt
        command: root