version: '3.4'

#Extension fields
x-image:
    &default-image
    image: infnpd/mucoll-ilc-framework:1.0-centos8

x-volumes:
    &default-volumes
    volumes:
        - $PWD/inputs/SoftCheck:$MAINDIR

x-environment:
    &default-environment
    environment:
        - DISPLAY=host.docker.internal:0

services:
    interactive:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash
    simulation:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash -c "source /opt/ilcsoft/v02-01-pre/init_ilcsoft.sh && cd $MAINDIR && ddsim --steeringFile clic_steer.py > sim.out"
    reco:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        command: /bin/bash -c "source /opt/ilcsoft/v02-01-pre/init_ilcsoft.sh && cd $MAINDIR && Marlin RecoConf.xml > reco.out"
    root:
        << : *default-image
        << : *default-volumes
        << : *default-environment
        privileged: true
        command: root